version: "3"
services:
  arangodb:
    image: arangodb/arangodb
    environment:
      - ARANGO_ROOT_PASSWORD=j0n@PRis.2014
    ports:
      - "8529:8529"
    volumes:
      - ./db_data:/var/lib/arangodb3
